# Client Dockerfile
FROM node:16

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the React app
RUN npm run build

# Expose the app on port 3000
EXPOSE 3000

# Serve the React app
CMD ["npx", "serve", "-s", "build"]
